import Foundation

// MARK: - Arabic situation labels

extension Situation {
    func localizedTitle(_ language: AppLanguage) -> String {
        language.pick(title, arabicTitle)
    }

    var arabicTitle: String {
        ArabicSituationTitles.values[id] ?? title
    }
}

private enum ArabicSituationTitles {
    static let values: [String: String] = [
        "beforeMarriage": "قبل الزواج",
        "lookingForSpouse": "عندما تبحث عن شريك صالح",
        "choosingSpouse": "عندما تختار شريك حياتك",
        "waitingForTiming": "عندما تنتظر ما قدّره الله لك",
        "worriedNeverMarry": "عندما تخشى ألا تتزوج",
        "strugglingPatience": "عندما يصعب عليك الصبر",
        "peaceInMarriage": "عندما تطلب السكينة في زواجك",
        "treatSpouseKindly": "عندما تحتاج إلى الإحسان في معاملة زوجك",
        "becomeBetterSpouse": "عندما تريد أن تكون زوجًا أفضل",
        "speakKindly": "عندما تحتاج إلى الكلام بلطف مع زوجك",
        "decidingTogether": "عندما تتخذان قرارًا معًا",
        "fairnessInMarriage": "عندما تحتاج إلى العدل في زواجك",
        "rebuildingTrust": "عندما تحاول إعادة بناء الثقة",
        "duaForFamily": "عندما تدعو لأسرتك",
        "feelingDistant": "عندما تشعر بالبعد عن زوجك",
        "marriageProblems": "عندما تواجه مشكلات زوجية",
        "constantlyArguing": "عندما يكثر الجدال بينكما",
        "spouseWrongedYou": "عندما يظلمك زوجك",
        "loweringAnger": "عندما يصعب عليك كظم الغيظ",
        "forgivingSpouse": "عندما تحتاج إلى مسامحة زوجك",
        "temptedToDivorce": "عندما تفكر في الطلاق بسبب خلاف",
        "marriageTested": "عندما يمر زواجك بابتلاء",
        "afraidWontLast": "عندما تخشى ألا يستمر زواجك",
        "questioningChoice": "عندما تراجع اختيارك",
        "trustingPlan": "عندما يصعب عليك الاطمئنان إلى تدبير الله",
        "trustingTiming": "عندما تصبر حتى يأتي ما قدّره الله لك",
        "stayOrLeave": "عندما تحتار بين البقاء والفراق",
        "raisingChildren": "عندما تربيان أبناءكما معًا",
        "prayingForChildren": "عندما تسأل الله الذرية الصالحة",
        "infertility": "عندما تواجه تأخر الإنجاب",
        "spouseAway": "عندما يكون زوجك بعيدًا عن البيت",
        "divorceUnavoidable": "عندما لا يكون هناك مفرّ من الطلاق",
        "afterDivorce": "عندما تتعافى بعد الطلاق",
        "grievingSpouse": "عندما تحزن على وفاة زوجك",
        "needGuidance": "عندما تحتاج إلى الهداية",
        "imanLow": "عندما يضعف إيمانك",
        "salahConnection": "عندما لا تجد الخشوع في الصلاة",
        "hardToPray": "عندما تصعب عليك الصلاة",
        "losingFocus": "عندما تفقد تركيزك",
        "forgettingBlessings": "عندما تنسى نعم الله",
        "strugglingGrateful": "عندما يصعب عليك الشكر",
        "fightingTemptation": "عندما تجاهد نفسك أمام المغريات",
        "madeAMistake": "عندما ترتكب خطأ",
        "forgiveYourself": "عندما يدفعك الخجل إلى اليأس من رحمة الله",
        "sameSin": "عندما تعود إلى الذنب نفسه",
        "selfControl": "عندما تجاهد لضبط نفسك",
        "scaredOfFuture": "عندما تخاف من المستقبل",
        "afraidOfFailure": "عندما تخاف من الفشل",
        "worriedTomorrow": "عندما تقلق بشأن الغد",
        "feelAlone": "عندما تشعر بالوحدة",
        "tooManyBurdens": "عندما تحمل أعباء كثيرة",
        "disappointed": "عندما تشعر بخيبة الأمل",
        "movingOn": "عندما تحاول المضي قدمًا",
        "everyoneAhead": "عندما يبدو أن الجميع سبقوك",
        "someoneHurtsYou": "عندما يؤذيك أحد",
        "needToForgive": "عندما تحتاج إلى العفو",
        "afraidPeopleThink": "عندما تخاف من كلام الناس",
        "feelingInsecure": "عندما تشعر بعدم الأمان",
        "facingRejection": "عندما تواجه الرفض",
        "worriedAboutRizq": "عندما تقلق بشأن الرزق",
        "strugglingFinancially": "عندما تمر بضائقة مالية",
        "hesitantCharity": "عندما تتردد في الصدقة",
        "comparingFinances": "عندما تقارن مالك بمال غيرك",
        "financialBurdens": "عندما تثقل عليك الأعباء المالية",
        "moneyStress": "عندما يسبب لك المال توترًا",
        "afraidToSpend": "عندما تخاف من الإنفاق في سبيل الله",
        "tomorrowRizq": "عندما تقلق بشأن رزق الغد",
        "workNoResults": "عندما تعمل ولا ترى نتيجة",
        "heartAttachedMoney": "عندما يتعلق قلبك بالمال",
        "barakahInWealth": "عندما تطلب البركة في مالك",
        "provisionDelayed": "عندما تظن أن رزقك تأخر",
        "salaryNotEnough": "عندما لا يكفي راتبك",
        "scaredStartBusiness": "عندما تخاف من بدء مشروع",
        "stuckFinancially": "عندما تشعر أن وضعك المالي لا يتحسن",
        "jealousOfSuccess": "عندما تغار من نجاح غيرك",
        "providingForFamily": "عندما تقلق بشأن الإنفاق على أسرتك",
        "afraidToRisk": "عندما تخاف من المخاطرة",
        "majorFinancialDecision": "عندما تتخذ قرارًا ماليًا كبيرًا",
        "impatientForResults": "عندما تستعجل النتائج",
        "everyoneAheadDuha": "عندما تشعر أن الجميع سبقوك",
        "payingBills": "عندما تقلق بشأن سداد الفواتير",
        "stressedAboutDebt": "عندما يرهقك الدَّين",
        "losingJob": "عندما تخاف من فقدان عملك",
        "savingsLow": "عندما تقل مدخراتك",
    ]
}
