# The ninety-nine names in the widely used order (at-Tirmidhi 3507 listing).
# (index, id, arabic, transliteration, english, arabic gloss, reflection en, reflection ar, quran ref or None)
NAMES = [
(1,"ar-rahman","الرَّحْمَنُ","Ar-Rahman","The Most Merciful","واسع الرحمة لكل خلقه","His mercy reaches you before you ask for it.","رحمته تسبقك قبل أن تطلبها.","1:3"),
(2,"ar-rahim","الرَّحِيمُ","Ar-Rahim","The Especially Merciful","الرحيم بعباده المؤمنين","A mercy kept for those who turn to Him.","رحمة خاصة بمن أقبل عليه.","1:3"),
(3,"al-malik","الْمَلِكُ","Al-Malik","The King","المالك لكل شيء","Everything you fear is under His rule.","كل ما تخشاه تحت ملكه.","59:23"),
(4,"al-quddus","الْقُدُّوسُ","Al-Quddus","The Most Holy","المنزّه عن كل نقص","Free of every flaw you find in yourself.","منزّه عن كل نقص تراه في نفسك.","59:23"),
(5,"as-salam","السَّلَامُ","As-Salam","The Source of Peace","السالم من كل عيب، واهب السلام","Peace comes from Him, not from circumstances.","السلام منه، لا من الظروف.","59:23"),
(6,"al-mumin","الْمُؤْمِنُ","Al-Mu’min","The Giver of Security","واهب الأمن والأمان","When nothing feels safe, He is safety itself.","حين لا تجد أمانًا، هو الأمن نفسه.","59:23"),
(7,"al-muhaymin","الْمُهَيْمِنُ","Al-Muhaymin","The Guardian","الرقيب الحافظ على كل شيء","Nothing about you goes unwatched or unheld.","لا شيء فيك يغيب عن رعايته.","59:23"),
(8,"al-aziz","الْعَزِيزُ","Al-‘Aziz","The Almighty","الغالب الذي لا يُغلب","His strength is never in short supply.","عزّته لا تنفد أبدًا.","59:23"),
(9,"al-jabbar","الْجَبَّارُ","Al-Jabbar","The Compeller, the Restorer","القاهر الذي يجبر الكسير","He mends what is broken, including hearts.","يجبر الكسر، والقلوب منه.","59:23"),
(10,"al-mutakabbir","الْمُتَكَبِّرُ","Al-Mutakabbir","The Supreme","المتعالي عن صفات الخلق","Greatness belongs to Him alone; you can rest.","الكبرياء له وحده، فاسترح.","59:23"),
(11,"al-khaliq","الْخَالِقُ","Al-Khaliq","The Creator","خالق كل شيء","He made you on purpose.","خلقك على قصد وحكمة.","59:24"),
(12,"al-bari","الْبَارِئُ","Al-Bari’","The Originator","الموجد من العدم","He brought you from nothing; He can bring ease from nothing.","أوجدك من العدم، ويوجد الفرج من العدم.","59:24"),
(13,"al-musawwir","الْمُصَوِّرُ","Al-Musawwir","The Fashioner","الذي أعطى كل شيء صورته","Your shape, your voice, your story: His design.","صورتك وصوتك وقصتك من تصويره.","59:24"),
(14,"al-ghaffar","الْغَفَّارُ","Al-Ghaffar","The Ever-Forgiving","كثير المغفرة","He forgives again, and again, and again.","يغفر مرة بعد مرة بعد مرة.","20:82"),
(15,"al-qahhar","الْقَهَّارُ","Al-Qahhar","The Subduer","القاهر فوق عباده","Every tyrant, every worry, is beneath Him.","كل جبّار وكل همّ دون قهره.","12:39"),
(16,"al-wahhab","الْوَهَّابُ","Al-Wahhab","The Bestower","كثير العطاء بلا عوض","He gives without being owed.","يعطي بلا مقابل.","3:8"),
(17,"ar-razzaq","الرَّزَّاقُ","Ar-Razzaq","The Provider","الذي يرزق كل مخلوق","Your provision is written and on its way.","رزقك مكتوب وآتٍ.","51:58"),
(18,"al-fattah","الْفَتَّاحُ","Al-Fattah","The Opener","الذي يفتح أبواب الخير والفرج","Closed doors are His to open.","الأبواب المغلقة بيده تُفتح.","34:26"),
(19,"al-alim","الْعَلِيمُ","Al-‘Alim","The All-Knowing","العالم بكل شيء","He knows what you cannot put into words.","يعلم ما تعجز عن قوله.","2:158"),
(20,"al-qabid","الْقَابِضُ","Al-Qabid","The Withholder","الذي يقبض الرزق والأرواح بحكمة","What is held back is held back with wisdom.","ما قُبض عنك قُبض بحكمة.","2:245"),
(21,"al-basit","الْبَاسِطُ","Al-Basit","The Extender","الذي يبسط الرزق والرحمة","Ease expands from His hand.","السعة تنبسط من يده.","2:245"),
(22,"al-khafid","الْخَافِضُ","Al-Khafid","The Abaser","الذي يخفض الجبابرة","No one stays high without His leave.","لا يبقى مرتفع إلا بإذنه.","56:3"),
(23,"ar-rafi","الرَّافِعُ","Ar-Rafi‘","The Exalter","الذي يرفع من يشاء","He can raise you when the world looks down on you.","يرفعك حين ينظر إليك الناس بازدراء.","6:83"),
(24,"al-muizz","الْمُعِزُّ","Al-Mu‘izz","The Honourer","الذي يمنح العزة","Real honour is given by Him, not by people.","العزة الحقيقية منه لا من الناس.","3:26"),
(25,"al-mudhill","الْمُذِلُّ","Al-Mudhill","The Humbler","الذي يذل من يشاء","Arrogance never lasts before Him.","لا يدوم كِبر أمامه.","3:26"),
(26,"as-sami","السَّمِيعُ","As-Sami‘","The All-Hearing","السامع لكل صوت","Your whisper reaches Him as clearly as a shout.","همسك يبلغه كما يبلغه صراخك.","2:127"),
(27,"al-basir","الْبَصِيرُ","Al-Basir","The All-Seeing","المبصر لكل شيء","Your unseen effort is fully seen.","جهدك الخفي مرئي عنده.","4:58"),
(28,"al-hakam","الْحَكَمُ","Al-Hakam","The Judge","الذي يحكم بين خلقه بالعدل","Injustice against you will not be the final word.","الظلم الذي أصابك ليس الكلمة الأخيرة.","22:69"),
(29,"al-adl","الْعَدْلُ","Al-‘Adl","The Just","العادل في حكمه وقضائه","He is never unfair, even when life feels so.","لا يظلم أبدًا وإن بدت الحياة ظالمة.","6:115"),
(30,"al-latif","اللَّطِيفُ","Al-Latif","The Subtle, the Kind","الرفيق بعباده في خفاء","He is gentle with you in ways you will only see later.","يلطف بك بطرق لا تراها إلا لاحقًا.","6:103"),
(31,"al-khabir","الْخَبِيرُ","Al-Khabir","The All-Aware","العالم بدقائق الأمور","He knows the details that no one else notices.","يعلم التفاصيل التي لا يلحظها أحد.","6:18"),
(32,"al-halim","الْحَلِيمُ","Al-Halim","The Forbearing","الذي لا يعجل بالعقوبة","He is patient with you; be patient with yourself.","يحلم عليك، فارفق بنفسك.","2:235"),
(33,"al-azim","الْعَظِيمُ","Al-‘Azim","The Magnificent","العظيم في ذاته وصفاته","Your problem is small next to His greatness.","مشكلتك صغيرة أمام عظمته.","2:255"),
(34,"al-ghafur","الْغَفُورُ","Al-Ghafur","The All-Forgiving","الذي يستر الذنوب ويمحوها","No sin is too large for His forgiveness.","لا ذنب أكبر من مغفرته.","2:173"),
(35,"ash-shakur","الشَّكُورُ","Ash-Shakur","The Appreciative","الذي يجازي القليل بالكثير","He rewards even the smallest sincere act.","يجازي أصغر عمل صادق.","35:30"),
(36,"al-ali","الْعَلِيُّ","Al-‘Ali","The Most High","العالي فوق كل شيء","Above every power that frightens you.","فوق كل قوة تخيفك.","2:255"),
(37,"al-kabir","الْكَبِيرُ","Al-Kabir","The Most Great","الكبير الذي لا أكبر منه","Allahu akbar: greater than whatever this is.","الله أكبر من كل ما تواجهه.","13:9"),
(38,"al-hafiz","الْحَفِيظُ","Al-Hafiz","The Preserver","الحافظ لكل شيء","You are kept, even when you cannot keep yourself.","أنت محفوظ وإن عجزت عن حفظ نفسك.","11:57"),
(39,"al-muqit","الْمُقِيتُ","Al-Muqit","The Sustainer","الذي يقوت كل حي","What you need to get through today is already provided.","ما تحتاجه ليومك مقدَّر لك.","4:85"),
(40,"al-hasib","الْحَسِيبُ","Al-Hasib","The Reckoner","الكافي والمحاسب","He is enough for you, and He keeps the account.","هو حسبك، وهو المحاسب.","4:6"),
(41,"al-jalil","الْجَلِيلُ","Al-Jalil","The Majestic","صاحب الجلال والعظمة","Majesty that makes everything else small.","جلال يصغر أمامه كل شيء.","55:27"),
(42,"al-karim","الْكَرِيمُ","Al-Karim","The Generous","الكريم الذي يعطي بلا حساب","He gives more than you asked, better than you asked.","يعطي أكثر مما سألت وأحسن مما سألت.","27:40"),
(43,"ar-raqib","الرَّقِيبُ","Ar-Raqib","The Watchful","المطلع على كل شيء","Watched over, not spied on.","مراقَب برعاية لا بتربص.","4:1"),
(44,"al-mujib","الْمُجِيبُ","Al-Mujib","The Responsive","الذي يجيب الداعي","Every du’a is answered, in one way or another.","كل دعاء مجاب بوجه من الوجوه.","11:61"),
(45,"al-wasi","الْوَاسِعُ","Al-Wasi‘","The All-Encompassing","الواسع في رحمته وعلمه","His mercy is wider than your mistakes.","رحمته أوسع من أخطائك.","2:268"),
(46,"al-hakim","الْحَكِيمُ","Al-Hakim","The All-Wise","صاحب الحكمة التامة","There is wisdom in this, even if you cannot see it yet.","في هذا حكمة وإن لم ترها بعد.","2:129"),
(47,"al-wadud","الْوَدُودُ","Al-Wadud","The Most Loving","المحب لعباده الصالحين","You are loved by the One who made you.","محبوب عند من خلقك.","11:90"),
(48,"al-majid","الْمَجِيدُ","Al-Majid","The Most Glorious","الواسع الكرم والمجد","Glory that lifts whoever turns to Him.","مجد يرفع من أقبل عليه.","11:73"),
(49,"al-baith","الْبَاعِثُ","Al-Ba‘ith","The Resurrector","الذي يبعث الخلق يوم القيامة","This is not the end of the story.","ليست هذه نهاية القصة.","22:7"),
(50,"ash-shahid","الشَّهِيدُ","Ash-Shahid","The Witness","الشاهد على كل شيء","He witnessed what was done to you.","شهد ما أصابك.","4:79"),
(51,"al-haqq","الْحَقُّ","Al-Haqq","The Truth","الحق الثابت الذي لا يزول","When everything is uncertain, He is certain.","حين يتزعزع كل شيء، هو الثابت.","22:6"),
(52,"al-wakil","الْوَكِيلُ","Al-Wakil","The Trustee","الذي يُتوكل عليه","Hand it to Him and let your shoulders drop.","سلّمه الأمر ودع كتفيك يرتاحان.","3:173"),
(53,"al-qawiyy","الْقَوِيُّ","Al-Qawiyy","The All-Strong","صاحب القوة الكاملة","Borrow your strength from His.","استمد قوتك من قوته.","22:40"),
(54,"al-matin","الْمَتِينُ","Al-Matin","The Firm","الشديد القوي الذي لا يتزعزع","He does not tire of holding you.","لا يكلّ من حملك.","51:58"),
(55,"al-waliyy","الْوَلِيُّ","Al-Waliyy","The Protecting Friend","الناصر والمتولي لعباده","You have an ally who never leaves.","لك وليّ لا يتخلى عنك.","4:45"),
(56,"al-hamid","الْحَمِيدُ","Al-Hamid","The Praiseworthy","المستحق للحمد كله","Worthy of praise in hardship and in ease.","يستحق الحمد في الشدة والرخاء.","14:8"),
(57,"al-muhsi","الْمُحْصِي","Al-Muhsi","The Enumerator","الذي أحصى كل شيء عددًا","Not one of your tears is uncounted.","ولا دمعة منك إلا محصاة.","72:28"),
(58,"al-mubdi","الْمُبْدِئُ","Al-Mubdi’","The Initiator","الذي بدأ الخلق","Every beginning starts with Him.","كل بداية تبدأ به.","10:34"),
(59,"al-muid","الْمُعِيدُ","Al-Mu‘id","The Restorer","الذي يعيد الخلق بعد فنائه","He can bring back what you thought was lost.","يعيد ما ظننته ضاع.","10:34"),
(60,"al-muhyi","الْمُحْيِي","Al-Muhyi","The Giver of Life","الذي يحيي الموتى والقلوب","He revives dead land and tired hearts.","يحيي الأرض الميتة والقلوب المتعبة.","30:50"),
(61,"al-mumit","الْمُمِيتُ","Al-Mumit","The Bringer of Death","الذي يميت الأحياء","Everything ends except Him; live for what lasts.","كل شيء ينتهي إلا هو؛ فاعمل لما يبقى.","3:156"),
(62,"al-hayy","الْحَيُّ","Al-Hayy","The Ever-Living","الحي الذي لا يموت","Your source of help never sleeps.","من تستعين به لا ينام.","2:255"),
(63,"al-qayyum","الْقَيُّومُ","Al-Qayyum","The Sustainer of All","القائم بنفسه، المقيم لغيره","He holds everything up, including you.","يقيم كل شيء، وأنت منه.","2:255"),
(64,"al-wajid","الْوَاجِدُ","Al-Wajid","The Finder","الغني الذي لا يعوزه شيء","Nothing you need is out of His reach.","لا شيء تحتاجه بعيد عنه.",None),
(65,"al-majid-2","الْمَاجِدُ","Al-Majid","The Noble","الكريم الواسع الفضل","Noble in how He treats those who fall.","كريم في معاملة من سقط.",None),
(66,"al-wahid","الْوَاحِدُ","Al-Wahid","The One","الواحد الذي لا شريك له","One direction to turn: simple, and enough.","وجهة واحدة تتجه إليها، وكفى.","13:16"),
(67,"al-ahad","الْأَحَدُ","Al-Ahad","The Unique","الأحد في ذاته وصفاته","There is no one like Him, so compare Him to no one.","لا مثيل له، فلا تقسه بأحد.","112:1"),
(68,"as-samad","الصَّمَدُ","As-Samad","The Eternal Refuge","الذي يُقصد في الحاجات","The One everyone leans on, who leans on no one.","الذي يقصده الجميع ولا يحتاج أحدًا.","112:2"),
(69,"al-qadir","الْقَادِرُ","Al-Qadir","The All-Able","القادر على كل شيء","Able to change your situation tonight.","قادر على تغيير حالك الليلة.","6:65"),
(70,"al-muqtadir","الْمُقْتَدِرُ","Al-Muqtadir","The Omnipotent","صاحب القدرة المطلقة","Nothing is impossible for Him.","لا مستحيل عنده.","18:45"),
(71,"al-muqaddim","الْمُقَدِّمُ","Al-Muqaddim","The Expediter","الذي يقدّم من يشاء","What comes early comes by His timing.","ما جاء مبكرًا جاء بتوقيته.",None),
(72,"al-muakhkhir","الْمُؤَخِّرُ","Al-Mu’akhkhir","The Delayer","الذي يؤخر من يشاء","A delay from Him is not a denial.","تأخيره ليس حرمانًا.",None),
(73,"al-awwal","الْأَوَّلُ","Al-Awwal","The First","الذي ليس قبله شيء","Before your worry existed, He was.","كان قبل أن يوجد همّك.","57:3"),
(74,"al-akhir","الْآخِرُ","Al-Akhir","The Last","الذي ليس بعده شيء","After your worry is gone, He remains.","يبقى بعد زوال همّك.","57:3"),
(75,"az-zahir","الظَّاهِرُ","Az-Zahir","The Manifest","الظاهر بآياته فوق كل شيء","His signs are everywhere you look.","آياته في كل ما تنظر إليه.","57:3"),
(76,"al-batin","الْبَاطِنُ","Al-Batin","The Hidden","القريب الذي لا تدركه الأبصار","Closer than what you can see.","أقرب مما ترى.","57:3"),
(77,"al-wali","الْوَالِي","Al-Wali","The Governor","المتولي لأمور الخلق","He runs the affairs you are losing sleep over.","يدبّر الأمور التي تسهر لأجلها.","13:11"),
(78,"al-mutaali","الْمُتَعَالِي","Al-Muta‘ali","The Most Exalted","المتعالي عن كل نقص","Exalted above every limitation.","متعالٍ عن كل قصور.","13:9"),
(79,"al-barr","الْبَرُّ","Al-Barr","The Source of Goodness","المحسن إلى عباده","Kindness comes from Him first.","الإحسان منه أولًا.","52:28"),
(80,"at-tawwab","التَّوَّابُ","At-Tawwab","The Acceptor of Repentance","الذي يقبل التوبة ويعين عليها","He turns to you before you turn to Him.","يقبل عليك قبل أن تقبل عليه.","2:37"),
(81,"al-muntaqim","الْمُنْتَقِمُ","Al-Muntaqim","The Avenger","الذي ينتقم من الظالمين","Justice will come; it is not yours to carry.","العدل آتٍ وليس عليك حمله.","32:22"),
(82,"al-afuww","الْعَفُوُّ","Al-‘Afuww","The Pardoner","الذي يمحو الذنوب","He erases, not just forgives.","يمحو الذنب لا يغفره فقط.","4:43"),
(83,"ar-rauf","الرَّءُوفُ","Ar-Ra’uf","The Most Kind","شديد الرحمة والرأفة","Tender with you when you are hardest on yourself.","رؤوف بك حين تقسو على نفسك.","2:143"),
(84,"malik-ul-mulk","مَالِكُ الْمُلْكِ","Malik-ul-Mulk","Owner of All Sovereignty","مالك الملك كله","Every kingdom, every boss, every system: His.","كل ملك وكل سلطة له.","3:26"),
(85,"dhul-jalali-wal-ikram","ذُو الْجَلَالِ وَالْإِكْرَامِ","Dhul-Jalali wal-Ikram","Lord of Majesty and Honour","صاحب الجلال والإكرام","Awe and generosity in the same Name.","الجلال والكرم في اسم واحد.","55:27"),
(86,"al-muqsit","الْمُقْسِطُ","Al-Muqsit","The Equitable","العادل في حكمه","He settles every account fairly.","يقضي في كل حساب بالقسط.","3:18"),
(87,"al-jami","الْجَامِعُ","Al-Jami‘","The Gatherer","الذي يجمع الخلق ليوم لا ريب فيه","He gathers what was scattered.","يجمع ما تفرّق.","3:9"),
(88,"al-ghaniyy","الْغَنِيُّ","Al-Ghaniyy","The Self-Sufficient","الغني عن كل شيء","He needs nothing from you, and still gives.","لا يحتاج شيئًا منك ومع ذلك يعطي.","2:263"),
(89,"al-mughni","الْمُغْنِي","Al-Mughni","The Enricher","الذي يغني من يشاء","Enough, then more than enough.","الكفاية ثم الزيادة.","9:28"),
(90,"al-mani","الْمَانِعُ","Al-Mani‘","The Preventer","الذي يمنع ما يشاء","What He kept from you protected you.","ما منعه عنك حماك.",None),
(91,"ad-darr","الضَّارُّ","Ad-Darr","The Distresser","الذي يقدّر الضر بحكمة","Even hardship passes through His wisdom.","حتى الضر يمر بحكمته.",None),
(92,"an-nafi","النَّافِعُ","An-Nafi‘","The Benefactor","الذي يقدّر النفع","All benefit traces back to Him.","كل نفع يعود إليه.",None),
(93,"an-nur","النُّورُ","An-Nur","The Light","نور السماوات والأرض","Light for a heart that feels dark.","نور لقلب يشعر بالظلمة.","24:35"),
(94,"al-hadi","الْهَادِي","Al-Hadi","The Guide","الذي يهدي من يشاء","Ask Him for the way; He shows it.","اسأله الطريق يُرِكَه.","22:54"),
(95,"al-badi","الْبَدِيعُ","Al-Badi‘","The Incomparable Originator","المبدع بلا مثال سابق","He creates without a template; He can create a way out.","يبدع بلا مثال سابق، ويبدع لك مخرجًا.","2:117"),
(96,"al-baqi","الْبَاقِي","Al-Baqi","The Everlasting","الباقي الذي لا يفنى","When everything fades, He stays.","حين يزول كل شيء، يبقى هو.","55:27"),
(97,"al-warith","الْوَارِثُ","Al-Warith","The Inheritor","الذي يرث الأرض ومن عليها","Everything returns to Him in the end.","إليه يرجع كل شيء في النهاية.","15:23"),
(98,"ar-rashid","الرَّشِيدُ","Ar-Rashid","The Guide to the Right Path","المرشد إلى الصواب","His guidance is never a wrong turn.","إرشاده لا يضل أبدًا.",None),
(99,"as-sabur","الصَّبُورُ","As-Sabur","The Patient","الذي لا يعجل على العصاة","He waits for you. Come back.","ينتظرك، فعُد.",None),
]
NOTE_EN = "This is the well-known enumeration. The hadith affirming ninety-nine names is in Sahih al-Bukhari 2736 and Sahih Muslim 2677 without a list; the listed order follows Jami‘ at-Tirmidhi 3507, whose enumeration some scholars grade weak."
NOTE_AR = "هذه هي القائمة المشهورة. ورد حديث الأسماء التسعة والتسعين في البخاري ٢٧٣٦ ومسلم ٢٦٧٧ دون سرد، وترتيبها هنا من جامع الترمذي ٣٥٠٧ الذي ضعّف بعض العلماء سرده."
