# One warm line per feeling: meets the person before the first du'a.
OPENINGS = {
"angry": ("Anger is a fire. Here is water.", "الغضب نار، وهذا ماء."),
"anxious": ("Your heart is racing. Let it slow down here.", "تتسارع دقات قلبك. خذ لحظة لتهدأ."),
"urgeToSin": ("The pull is real. So is the way out.", "قد تشتد الرغبة في المعصية، لكن باب الرجوع مفتوح."),
"confident": ("Good. Now anchor it to the One who gave it.", "الثقة نعمة. اربطها بمن وهبك إياها."),
"confused": ("You don’t need clarity yet. You need Him.", "قد لا تتضح لك الأمور الآن، فاستعن بالله."),
"content": ("This calm is a gift. Say thank you for it.", "هذه الطمأنينة نعمة، فاشكر الله عليها."),
"depressed": ("It’s heavy, and it’s dark. You are not alone in it.", "قد يبدو كل شيء ثقيلًا ومظلمًا، لكنك لست وحدك."),
"doubtful": ("Doubt is a question, not a verdict.", "الشك سؤال، لا حكم."),
"grateful": ("Gratitude keeps blessings close.", "الشكر يُبقي النعم قريبة."),
"greedy": ("What you chase is His to give. Ask instead.", "ما تسعى إليه من رزق بيد الله، فاسأله من فضله."),
"guilty": ("Guilt means your heart still works. Bring it back.", "الشعور بالذنب دليل على أن قلبك حي. عُد إلى الله."),
"happy": ("Joy is from Him. Send it back up as praise.", "الفرح نعمة من الله، فاحمده عليها."),
"hurt": ("Someone hurt you. He saw it.", "لقد آذاك أحدهم، والله يعلم ما أصابك."),
"indecisive": ("You can’t see every road. He can.", "لا ترى كل الطرق، وهو يراها."),
"hypocritical": ("Fearing hypocrisy is a sign of sincerity.", "الخوف من النفاق علامة على الصدق."),
"jealous": ("What they have was written for them. Ask for yours.", "ما عندهم رزق كتبه الله لهم، فاسأله من فضله."),
"lazy": ("Small words, said now, are enough to begin.", "كلمات يسيرة تقولها الآن تكفي للبدء."),
"lonely": ("Alone in a room, never alone in the world.", "قد تكون وحدك في غرفتك، لكنك لست وحدك في هذا العالم."),
"lost": ("The way isn’t clear yet. Ask the One who knows it.", "الطريق غير واضح بعد. اسأل من يعلمه."),
"nervous": ("Breathe. Then hand the outcome over.", "تنفّس بهدوء، ثم فوّض أمرك إلى الله."),
"overwhelmed": ("You were never meant to carry all of it.", "لست مضطرًا إلى حمل كل هذه الأعباء وحدك."),
"regret": ("What’s done is done. What’s next is still yours.", "ما مضى مضى، وما يأتي ما زال بيدك."),
"sad": ("Sadness is allowed here. So is hope.", "لا بأس أن تحزن، وأن يبقى في قلبك أمل."),
"scared": ("Fear shrinks when you name Who is bigger.", "يخفّ الخوف حين تتذكّر عظمة الله."),
"suicidal": ("You matter. Please reach out to someone now, and stay with these words.", "أنت مهم. تواصل مع أحد الآن، وابقَ مع هذه الكلمات."),
"tired": ("Rest is not failure. Ask for strength.", "الراحة ليست فشلًا. اطلب القوة."),
"unloved": ("The One who made you loves you. Start there.", "من خلقك يحبك. ابدأ من هنا."),
"weak": ("Weakness is where His strength enters.", "حين تشعر بالضعف، اطلب العون من الله."),
"bored": ("Emptiness is space. Fill it with remembrance.", "الفراغ فرصة، فاملأ وقتك بذكر الله."),
"impatient": ("His timing has never been late.", "كل شيء عند الله بقدر وفي وقته."),
"hopeful": ("Hope is a form of trust. Keep it alive.", "الأمل صورة من الثقة، فأبقه حيًّا."),
"grieving": ("Loss is real. So is the reunion.", "الفقد حقيقي، واللقاء حقيقي أيضًا."),
"seekingForgiveness": ("The door back is open. It always was.", "باب العودة مفتوح، وما زال كذلك."),
}
