# One warm line per feeling: meets the person before the first du'a.
OPENINGS = {
"angry": ("Anger is a fire. Here is water.", "الغضب نار، وهذه ماء."),
"anxious": ("Your heart is racing. Let it slow down here.", "قلبك يتسارع. دعه يهدأ هنا."),
"urgeToSin": ("The pull is real. So is the way out.", "الجذب حقيقي، والمخرج حقيقي أيضًا."),
"confident": ("Good. Now anchor it to the One who gave it.", "جميل. اربطها الآن بمن وهبك إياها."),
"confused": ("You don’t need clarity yet. You need Him.", "لا تحتاج الوضوح الآن، بل تحتاجه هو."),
"content": ("This calm is a gift. Say thank you for it.", "هذا السكون نعمة، فاشكرها."),
"depressed": ("It’s heavy, and it’s dark. You are not alone in it.", "ثقيل ومظلم، لكنك لست وحدك فيه."),
"doubtful": ("Doubt is a question, not a verdict.", "الشك سؤال، لا حكم."),
"grateful": ("Gratitude keeps blessings close.", "الشكر يُبقي النعم قريبة."),
"greedy": ("What you chase is His to give. Ask instead.", "ما تلاحقه بيده. اسأله بدل الملاحقة."),
"guilty": ("Guilt means your heart still works. Bring it back.", "الشعور بالذنب دليل أن قلبك حي. عُد به."),
"happy": ("Joy is from Him. Send it back up as praise.", "الفرح منه، فأعده إليه حمدًا."),
"hurt": ("Someone hurt you. He saw it.", "أحدهم آذاك، وهو رأى ذلك."),
"indecisive": ("You can’t see every road. He can.", "لا ترى كل الطرق، وهو يراها."),
"hypocritical": ("Fearing hypocrisy is a sign of sincerity.", "الخوف من النفاق علامة على الصدق."),
"jealous": ("What they have was written for them. Ask for yours.", "ما عندهم كُتب لهم. اسأل ما كُتب لك."),
"lazy": ("Small words, said now, are enough to begin.", "كلمات يسيرة تقولها الآن تكفي للبدء."),
"lonely": ("Alone in a room, never alone in the world.", "وحيد في غرفة، لا وحيد في العالم."),
"lost": ("The way isn’t clear yet. Ask the One who knows it.", "الطريق غير واضح بعد. اسأل من يعلمه."),
"nervous": ("Breathe. Then hand the outcome over.", "تنفس، ثم سلّم النتيجة."),
"overwhelmed": ("You were never meant to carry all of it.", "لم تُخلق لتحمل كل هذا."),
"regret": ("What’s done is done. What’s next is still yours.", "ما مضى مضى، وما يأتي ما زال بيدك."),
"sad": ("Sadness is allowed here. So is hope.", "الحزن مسموح هنا، والأمل كذلك."),
"scared": ("Fear shrinks when you name Who is bigger.", "الخوف يصغر حين تذكر من هو أكبر."),
"suicidal": ("You matter. Please reach out to someone now, and stay with these words.", "أنت مهم. تواصل مع أحد الآن، وابقَ مع هذه الكلمات."),
"tired": ("Rest is not failure. Ask for strength.", "الراحة ليست فشلًا. اطلب القوة."),
"unloved": ("The One who made you loves you. Start there.", "من خلقك يحبك. ابدأ من هنا."),
"weak": ("Weakness is where His strength enters.", "من الضعف يدخل عونه."),
"bored": ("Emptiness is space. Fill it with remembrance.", "الفراغ مساحة، فاملأها ذكرًا."),
"impatient": ("His timing has never been late.", "توقيته لم يتأخر قط."),
"hopeful": ("Hope is a form of trust. Keep it alive.", "الأمل صورة من الثقة، فأبقه حيًّا."),
"grieving": ("Loss is real. So is the reunion.", "الفقد حقيقي، واللقاء حقيقي أيضًا."),
"seekingForgiveness": ("The door back is open. It always was.", "باب العودة مفتوح، وما زال كذلك."),
}
